import { useEffect, useState, type ReactNode } from "react";

import { postJson } from "./api";
import type { JobRecord, PurgePlan, QuarantinePlan, RelationshipPlan, RestorePlan } from "./types";

function Modal({ close, children, danger = false }: { close: () => void; children: ReactNode; danger?: boolean }) {
  useEffect(() => {
    const escape = (event: KeyboardEvent) => { if (event.key === "Escape") close(); };
    window.addEventListener("keydown", escape);
    return () => window.removeEventListener("keydown", escape);
  }, [close]);
  return <div className="modal-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) close(); }}><section className={`modal management-modal${danger ? " management-modal-danger" : ""}`}>{children}</section></div>;
}

function Top({ eyebrow, title, close }: { eyebrow: string; title: string; close: () => void }) {
  return <div className="management-modal-top"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div><button className="button secondary" onClick={close}>닫기</button></div>;
}

function PlanCheck({ sha, blockers }: { sha: string; blockers: string[] }) {
  return <div className={blockers.length ? "management-plan blocked" : "management-plan ready"}><strong>{blockers.length ? "실행 차단" : "현재 계획 실행 가능"}</strong><code>{sha}</code>{blockers.map((value) => <span key={value}>{value}</span>)}</div>;
}

export function RelationshipManager({ leftId, rightId, currentDecisionId, close, done }: { leftId: string; rightId: string; currentDecisionId?: number | null; close: () => void; done: () => void }) {
  const [verdict, setVerdict] = useState<RelationshipPlan["verdict"]>("same_work_distinct_variant");
  const [variantKind, setVariantKind] = useState("other");
  const [note, setNote] = useState("");
  const [plan, setPlan] = useState<RelationshipPlan>();
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const preview = async () => { setBusy(true); setError(""); try { setPlan(await postJson<RelationshipPlan>("/api/management/relationships/preview", { left_file_id: leftId, right_file_id: rightId, verdict, variant_kind: variantKind, note })); } catch (reason) { setError(reason instanceof Error ? reason.message : "계획을 만들지 못했습니다."); } finally { setBusy(false); } };
  const apply = async () => { if (!plan) return; setBusy(true); setError(""); try { await postJson("/api/management/relationships/apply", { left_file_id: leftId, right_file_id: rightId, verdict, variant_kind: variantKind, note, confirm_count: plan.item_count, confirm_plan_sha256: plan.plan_sha256 }); done(); close(); } catch (reason) { setError(reason instanceof Error ? reason.message : "판정을 저장하지 못했습니다."); } finally { setBusy(false); } };
  const cancel = async () => { if (!currentDecisionId || !window.confirm("현재 사람 판정을 취소하고 두 파일을 다시 미배정 상태로 돌릴까요?")) return; setBusy(true); try { await postJson(`/api/management/relationships/${currentDecisionId}/cancel`, {}); done(); close(); } catch (reason) { setError(reason instanceof Error ? reason.message : "판정을 취소하지 못했습니다."); } finally { setBusy(false); } };
  return <Modal close={close}><Top eyebrow="HUMAN RELATIONSHIP · 1.3.2" title="두 파일 관계 확정" close={close}/><p className="management-description">현재 fingerprint에 묶인 사람 판단을 저장합니다. 파일 내용이 바뀌면 이 판단을 자동 재사용하지 않습니다.</p>{error && <div className="inline-error">{error}</div>}<div className="management-form"><label>판정<select value={verdict} onChange={(event) => { setVerdict(event.target.value as RelationshipPlan["verdict"]); setPlan(undefined); }}><option value="same_work_distinct_variant">같은 작품의 다른 판본·부속</option><option value="distinct_work">제목만 같은 다른 작품</option><option value="same_content">같은 내용</option></select></label><label>판본 종류<select value={variantKind} onChange={(event) => { setVariantKind(event.target.value); setPlan(undefined); }}><option value="other">기타/extra</option><option value="revision">개정판</option><option value="adult">성인판</option><option value="translation">번역판</option><option value="base">기본판</option></select></label><label className="management-wide">판단 메모<input value={note} onChange={(event) => { setNote(event.target.value); setPlan(undefined); }} placeholder="왜 이 관계로 판단했는지 선택 입력"/></label></div>{plan && <PlanCheck sha={plan.plan_sha256} blockers={plan.blocked_reasons}/>}<footer><button className="button secondary" disabled={busy} onClick={preview}>{busy ? "확인 중…" : "계획 확인"}</button>{currentDecisionId && <button className="button danger" disabled={busy} onClick={cancel}>현재 판정 취소</button>}<button className="button primary" disabled={busy || !plan?.apply_available} onClick={apply}>{plan?.mode === "correction" ? "판정 정정 저장" : "판정 저장"}</button></footer></Modal>;
}

export function QuarantineManager({ sourceId, keepId, close, started }: { sourceId: string; keepId?: string | null; close: () => void; started: (job: JobRecord) => void }) {
  const [plan, setPlan] = useState<QuarantinePlan>(); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const preview = async () => { setBusy(true); setError(""); try { setPlan(await postJson<QuarantinePlan>("/api/management/quarantine/preview", { source_file_id: sourceId, keep_file_id: keepId || null })); } catch (reason) { setError(reason instanceof Error ? reason.message : "격리 계획을 만들지 못했습니다."); } finally { setBusy(false); } };
  const apply = async () => { if (!plan) return; setBusy(true); try { const job = await postJson<JobRecord>("/api/management/quarantine/apply", { source_file_id: sourceId, keep_file_id: keepId || null, confirm_count: 1, confirm_plan_sha256: plan.plan_sha256 }); started(job); close(); } catch (reason) { setError(reason instanceof Error ? reason.message : "격리를 시작하지 못했습니다."); setBusy(false); } };
  return <Modal close={close}><Top eyebrow="USER QUARANTINE · 1.3.2" title="사용자 승인 격리" close={close}/><p className="management-description">자동 중복이라고 주장하지 않고, 사용자가 이 판본을 보유 목록에서 제외했다는 처분을 기록합니다.</p>{error && <div className="inline-error">{error}</div>}{plan && <><div className="management-impact"><span>대상<strong>{plan.source.name}</strong></span><span>유지 파일<strong>{plan.keep?.name ?? "지정 없음"}</strong></span><span>대표 교체<strong>{plan.replacement_representative?.name ?? "없음"}</strong></span><span>관계 영향<strong>{plan.retired_work ? "작품 퇴역" : plan.retired_variant ? "판본 퇴역" : "활성 유지"}</strong></span></div><PlanCheck sha={plan.plan_sha256} blockers={plan.blocked_reasons}/></>}<footer><button className="button secondary" disabled={busy} onClick={preview}>격리 계획 확인</button><button className="button danger" disabled={busy || !plan?.apply_available} onClick={apply}>격리 실행</button></footer></Modal>;
}

export function RestoreManager({ operationId, defaultReferenceId, close, started }: { operationId: number; defaultReferenceId?: string | null; close: () => void; started: (job: JobRecord) => void }) {
  const [referenceId, setReferenceId] = useState(defaultReferenceId ?? ""); const [verdict, setVerdict] = useState<RestorePlan["verdict"]>("same_work_distinct_variant"); const [note, setNote] = useState(""); const [plan, setPlan] = useState<RestorePlan>(); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const preview = async () => { setBusy(true); setError(""); try { setPlan(await postJson<RestorePlan>("/api/management/quarantine/restore/preview", { operation_id: operationId, reference_file_id: referenceId || null, verdict, note })); } catch (reason) { setError(reason instanceof Error ? reason.message : "복원 계획을 만들지 못했습니다."); } finally { setBusy(false); } };
  const apply = async () => { if (!plan) return; setBusy(true); try { const job = await postJson<JobRecord>("/api/management/quarantine/restore/apply", { operation_id: operationId, reference_file_id: referenceId || null, verdict, note, confirm_count: 1, confirm_plan_sha256: plan.plan_sha256 }); started(job); close(); } catch (reason) { setError(reason instanceof Error ? reason.message : "복원을 시작하지 못했습니다."); setBusy(false); } };
  return <Modal close={close}><Top eyebrow="RESTORE AS DISTINCT · 1.3.2" title="중복 아님으로 복원" close={close}/><p className="management-description">원래 경로가 비어 있을 때만 복원하며, 다음 중복 검사에서 다시 격리되지 않도록 비교 파일과의 관계를 함께 저장합니다.</p>{error && <div className="inline-error">{error}</div>}<div className="management-form"><label className="management-wide">비교할 활성 파일 ID<input value={referenceId} onChange={(event) => { setReferenceId(event.target.value); setPlan(undefined); }} placeholder="같은 작품 또는 구분할 작품의 file ID"/></label><label>복원 관계<select value={verdict} onChange={(event) => { setVerdict(event.target.value as RestorePlan["verdict"]); setPlan(undefined); }}><option value="same_work_distinct_variant">같은 작품의 다른 판본</option><option value="distinct_work">제목만 같은 다른 작품</option></select></label><label>메모<input value={note} onChange={(event) => { setNote(event.target.value); setPlan(undefined); }}/></label></div>{plan && <><div className="management-paths"><small>격리: {plan.quarantine_path}</small><small>복원: {plan.destination_path}</small></div><PlanCheck sha={plan.plan_sha256} blockers={plan.blocked_reasons}/></>}<footer><button className="button secondary" disabled={busy} onClick={preview}>복원 계획 확인</button><button className="button primary" disabled={busy || !plan?.apply_available} onClick={apply}>복원 실행</button></footer></Modal>;
}

export function PurgeManager({ operationIds, close, started }: { operationIds: number[]; close: () => void; started: (job: JobRecord) => void }) {
  const [plan, setPlan] = useState<PurgePlan>(); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  useEffect(() => { setBusy(true); postJson<PurgePlan>("/api/management/quarantine/purge/preview", { operation_ids: operationIds }).then(setPlan).catch((reason) => setError(reason.message)).finally(() => setBusy(false)); }, [operationIds]);
  const apply = async () => { if (!plan) return; setBusy(true); try { const job = await postJson<JobRecord>("/api/management/quarantine/purge/apply", { operation_ids: operationIds, confirm_count: plan.item_count, confirm_plan_sha256: plan.plan_sha256 }); started(job); close(); } catch (reason) { setError(reason instanceof Error ? reason.message : "영구 삭제를 시작하지 못했습니다."); setBusy(false); } };
  return <Modal close={close} danger><Top eyebrow="IRREVERSIBLE PURGE · 1.3.2" title="격리 파일 영구 삭제" close={close}/><div className="management-danger-note"><strong>파일 bytes는 복구할 수 없습니다.</strong><span>아래 대상과 용량을 확인한 뒤 영구 삭제 실행을 누르세요. DB의 파일 identity, fingerprint와 operation 이력은 남습니다.</span></div>{error && <div className="inline-error">{error}</div>}{plan && <><div className="management-impact"><span>선택 항목<strong>{plan.item_count}개</strong></span><span>회수 용량<strong>{new Intl.NumberFormat("ko-KR").format(plan.total_size)} bytes</strong></span></div><div className="management-purge-list">{plan.items.map((item) => <span key={item.operation_id}><b>{item.name}</b><small>{item.age_days ?? "?"}일 보관 · {item.size.toLocaleString("ko-KR")} bytes</small></span>)}</div><PlanCheck sha={plan.plan_sha256} blockers={plan.blocked_reasons}/></>}<footer><button className="button danger" disabled={busy || !plan?.apply_available} onClick={apply}>영구 삭제 실행</button></footer></Modal>;
}
